name: KakaoTalk Send Message

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: KakaoTalk CI Action
        uses: Alfex4936/kakaotalk-ci-action@v1.0.1
        with:
          kakao_access_token: ${{secrets.KAKAO_ACCESS_TOKEN}}
          function_name: send_to_me_custom
          template_id: "93112"
          template_args: '{"title": "test", "desc": "설명"}'
